name: GitHub Action to deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Yarn & Node install cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build pages
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
